<a href="https://colab.research.google.com/github/nikita082000/DTEY/blob/%D0%9A%D0%A1%D0%92%D0%94/Nikytenko_hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
vector_20 = np.arange(1, 21)
print("Вектор натуральних чисел:\n", vector_20)

Вектор натуральних чисел:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
ones_matrix = np.ones((4, 4))
print("\nМатриця 4x4 з одиниць:\n", ones_matrix)


Матриця 4x4 з одиниць:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
random_matrix_5x5 = np.random.uniform(-1, 1, (5, 5))
print("Матриця 5x5 (від -1 до 1):\n", random_matrix_5x5)

Матриця 5x5 (від -1 до 1):
 [[ 0.1962725  -0.23366858 -0.65131344 -0.83316584  0.18930703]
 [-0.83083101  0.88879929 -0.97781373 -0.05232897 -0.98961107]
 [ 0.76360765 -0.42431908 -0.43392894 -0.13583391 -0.40401746]
 [-0.36462617  0.40264989 -0.7194053  -0.86263986  0.23478699]
 [ 0.90731988  0.94050562 -0.09233078  0.64393251  0.18780089]]


In [5]:
random_matrix_3x3 = np.random.rand(3, 3)
print("\nМатриця 3x3 (від 0 до 1):\n", random_matrix_3x3)


Матриця 3x3 (від 0 до 1):
 [[0.55980768 0.1922671  0.81907752]
 [0.3042382  0.96607744 0.59118992]
 [0.11132718 0.9663369  0.36877826]]


In [6]:
arr1 = np.random.randint(1, 21, 6)
arr2 = np.random.randint(1, 21, 6)

print(f"Масив 1: {arr1}")
print(f"Масив 2: {arr2}")
print("Додавання:", arr1 + arr2)
print("Віднімання:", arr1 - arr2)
print("Множення:", arr1 * arr2)

Масив 1: [12 10  3  4  4  4]
Масив 2: [ 6 17  3  6 19  5]
Додавання: [18 27  6 10 23  9]
Віднімання: [  6  -7   0  -2 -15  -1]
Множення: [ 72 170   9  24  76  20]


In [7]:
mat_a = np.random.randint(1, 6, (3, 2))
mat_b = np.random.randint(1, 6, (2, 4))
result_dot = np.dot(mat_a, mat_b)

print("Матриця 3x2:\n", mat_a)
print("Матриця 2x4:\n", mat_b)
print("Результат множення (3x4):\n", result_dot)

Матриця 3x2:
 [[1 2]
 [5 3]
 [5 3]]
Матриця 2x4:
 [[2 3 3 3]
 [2 5 3 3]]
Результат множення (3x4):
 [[ 6 13  9  9]
 [16 30 24 24]
 [16 30 24 24]]


In [8]:
mat_to_transpose = np.random.rand(3, 3)
print("Оригінальна матриця:\n", mat_to_transpose)
print("Транспонована матриця:\n", mat_to_transpose.T)

Оригінальна матриця:
 [[0.25329633 0.66338331 0.14199801]
 [0.30426008 0.81310034 0.96925789]
 [0.92400047 0.08822634 0.69119522]]
Транспонована матриця:
 [[0.25329633 0.30426008 0.92400047]
 [0.66338331 0.81310034 0.08822634]
 [0.14199801 0.96925789 0.69119522]]


In [9]:
mat_c = np.random.randint(1, 11, (3, 3))
mat_d = np.random.randint(1, 11, (3, 3))
print("\nМатриця C:\n", mat_c)
print("Матриця D:\n", mat_d)
print("Різниця C - D:\n", mat_c - mat_d)


Матриця C:
 [[6 1 2]
 [2 3 9]
 [9 2 4]]
Матриця D:
 [[1 3 5]
 [5 9 7]
 [8 3 6]]
Різниця C - D:
 [[ 5 -2 -3]
 [-3 -6  2]
 [ 1 -1 -2]]


In [10]:
mat_e = np.random.randint(-5, 6, (3, 3))
mat_f = np.random.randint(-5, 6, (3, 3))
print("Матриця E:\n", mat_e)
print("Матриця F:\n", mat_f)
print("Матричний добуток E * F:\n", np.dot(mat_e, mat_f))

Матриця E:
 [[ 3 -1 -5]
 [-4  2 -4]
 [-3  1  1]]
Матриця F:
 [[-3  5  2]
 [ 0  0 -1]
 [-3 -1  3]]
Матричний добуток E * F:
 [[  6  20  -8]
 [ 24 -16 -22]
 [  6 -16  -4]]


In [12]:
mat_g = np.random.uniform(-1, 1, (3, 3))
row_sums = mat_g.sum(axis=1).reshape(-1, 1)

In [13]:
print("\nМатриця G:\n", mat_g)
print("Вектор-стовпчик сум рядків:\n", row_sums)


Матриця G:
 [[-0.00124318  0.27000506  0.43288582]
 [ 0.11935295 -0.62326723  0.41160921]
 [ 0.62863652 -0.67746748 -0.45748957]]
Вектор-стовпчик сум рядків:
 [[ 0.7016477 ]
 [-0.09230508]
 [-0.50632052]]
